config/routes.rb
Webapp::Application.routes.draw do
  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"  }
  
  resources :users
  resources :bookmarks
  
  get '/n', :to => 'bookmarks#index_new'
  get '/f', :to => 'bookmarks#index_favorites'
  get '/a', :to => 'bookmarks#index_archive'
  get '/o', :to => 'bookmarks#index_oldest'
  get '/s/:site_id', :to => 'bookmarks#by_site'
  
  post '/a/:bookmark', :to => 'bookmarks#archive'
  
  # redirect shortened urls
  get '/r/:short_url', :to => 'shortened_links#translate'
  
  # admin stuff
  post '/users/lock/:id' => 'users#lock'
  post '/users/unlock/:id' => 'users#unlock'
  
  # internal background stuff
  get 'internal/age' => 'background_tasks#age_bookmarks'
  get 'internal/expire' => 'background_tasks#expire_bookmarks'

  # health checks for the app
  get 'status/ready', to: 'health_checks#readiness'
  get 'status/live', to: 'health_checks#liveness'
end

app/models/bookmark.rb
require 'open-uri'

class Bookmark < ActiveRecord::Base
  
  # relations
  belongs_to :user
  has_one :resource
  
  # hooks
  before_create :initialize_bookmark
  
  self.per_page = 15
  
  def self.create_or_retrieve(params)

    # check if the url is already known
    rsrc = Resource.find_by_url params[:url]
    if rsrc
      # check for a dupilcate within the user's list of bookmarks
      bookmark = Bookmark.find_by_resource_id_and_user_id rsrc.id, params[:user_id]
      
      if bookmark.nil?
        bookmark = Bookmark.create_bookmark params
      end
      
    else
      # resource does not exist, so the bookmark can't exist
      bookmark = Bookmark.create_bookmark params
    end
    
    bookmark 
  end

  def self.create_bookmark(params)
    # the url to add
    url = params[:url]
    
    # scrap the site's favicon
    host = URI(url).host
    site = Site.find_by_host(host)
    
    if site.nil? 
      file = Site.scrap_favicon host
      if file
        # create a new resource record
        site = Site.new
        site.host = host
        site.favicon = file
        site.save
      else
        # load the default favicon
        site = Site.find_by_host('default')
      end
    end
    
    # retrieve / create a resource
    rsrc = Resource.find_by_url url
    if rsrc.nil?
      rsrc = Resource.new
      rsrc.url = url
      rsrc.title = Resource.scrap_title url
      rsrc.site_id = site.id
      rsrc.save!
    end
    
    # create a new bookmark
    bookmark = Bookmark.new
    
    # complete the bookmark record
    bookmark.user_id = params[:user_id]
    bookmark.view_count = 0
    bookmark.url_shortened = Bookmark.generate_short_url(url, params[:user_id]) 
    bookmark.url_shortened_pub = Bookmark.generate_public_short_url(url, params[:user_id])
    bookmark.description = params[:description]
    bookmark.description = rsrc.title if bookmark.description.nil?
    bookmark.time_to_expiration = 128
    bookmark.archived = false
    bookmark.expired = false
    
    # add the site_id to the bookmark
    bookmark.site_id = site.id
    
    # add the resource id to the bookmark
    bookmark.resource_id = rsrc.id
    
    # save the new bookmark
    bookmark.save!
    bookmark
  end
  
    
  # Generate a (private) shortened link from a url
  def self.generate_short_url(orig_url, user_id=nil)
       
    # generate a new random key
    begin
      unique_key = self.generate_random_string(8)
    end while Bookmark.find_by_url_shortened unique_key
    
    return unique_key
    
  end
  
  # Generate a (public) shortened link from a url
  def self.generate_public_short_url(orig_url, user_id=nil)
     
    # generate a new random key
    begin
      unique_key = self.generate_random_string(8)
    end while Bookmark.find_by_url_shortened_pub unique_key
    
    return unique_key
    
  end
  
  # Generate a random string
  def self.generate_random_string(size = 8)
    # not doing uppercase as url is case insensitive
    charset = ('a'..'z').to_a + (0..9).to_a
    (0...size).map{ charset.to_a[rand(charset.size)] }.join
  end
  
  protected 
  
  def initialize_bookmark
    
  end
end

app/controllers/bookmarks_controller.rb
require 'addressable/uri'

class BookmarksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :protect_bookmark!, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  def index
    @bookmark = Bookmark.new
    @bookmarks = bookmark_stream_all
    @features = bookmark_stream_featured
        
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
  end

  # GET /bookmarks/n
  def index_new
    @bookmark = Bookmark.new
    @bookmarks = bookmark_stream_new
    @features = bookmark_stream_featured
    
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
    
    render :index
  end
  
  # GET /bookmarks/f
  def index_favorites
    @bookmark = Bookmark.new
    @bookmarks = bookmark_stream_favorites
    
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
    
    render :index_noscroll
  end
  
  # GET /bookmarks/a
  def index_archive
    @bookmark = Bookmark.new
    @bookmarks = bookmark_stream_archived
    
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
    
    render :index
  end
  
  # GET /bookmarks/o
  def index_oldest
    @bookmark = Bookmark.new
    @bookmarks = bookmark_stream_oldest
    
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
    
    render :index
  end
  
  # GET /s/:site_id
  def by_site
    @bookmark = Bookmark.new
    @bookmarks = bookmark_stream_by_site params[:site_id]
    
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
    
    render :index_noscroll
  end
  
  
  # GET /bookmarks/:id
  def show

  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/:id/edit
  def edit
    @bookmark_count_all = bookmark_count_all current_user
    @bookmark_count_unread = bookmark_count_unread current_user
    @bookmark_count_archived = bookmark_count_archived current_user
  end

  # POST /bookmarks
  def create
    Bookmark.create_or_retrieve bookmark_params
    @bookmarks = bookmark_stream_all
    @bookmark = Bookmark.new
    
    redirect_to bookmarks_url
  end

  # PATCH/PUT /bookmarks/:id
  def update

    if @bookmark.update(bookmark_params)
      @bookmarks = bookmark_stream_all
      @bookmark = Bookmark.new

      redirect_to bookmarks_url
    else
      render action: 'edit'
    end
  end

  # DELETE /bookmarks/:id
  def destroy
    @bookmark.destroy
    redirect_to bookmarks_url
  end

  # POST /a/:bookmark
  def archive
    bookmark = Bookmark.find(params[:bookmark])
    if bookmark
      bookmark.archived = true
      bookmark.save!
    end
    
    redirect_to(request.referrer || root_path) 
  end
  
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  # Avoid that someone can access other user's bookmarks
  def protect_bookmark!
    # protect bookmarks from other users
    redirect_to bookmarks_url if @bookmark.user_id != current_user.id
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bookmark_params
    if params[:bookmark]
      p = params[:bookmark].permit(:url,:description)
      p[:user_id] = current_user.id
      p[:url] = normalize_url params[:url] if params[:url]
    else
      p = {:url => normalize_url( params.require(:url)), :user_id => current_user.id }
    end

    puts p.to_s
    return p
  end

  # normalize the url
  def normalize_url(url)
    uri = Addressable::URI.parse url
    if uri.scheme == nil
      uri = Addressable::URI.parse ("http://" + url)
    end
    uri.normalize.to_s
  end
  
  #
  # helpers to select the right bookmarks
  #
  def bookmark_stream_all
    Bookmark.where(:user_id => current_user.id, :expired => false, :archived => false).paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def bookmark_stream_oldest
    Bookmark.where(:user_id => current_user.id, :expired => false, :archived => false).paginate(:page => params[:page]).order('created_at ASC')
  end
  
  def bookmark_stream_archived
    Bookmark.where(:user_id => current_user.id, :expired => false, :archived => true).paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def bookmark_stream_new
    Bookmark.where(:user_id => current_user.id, :view_count => 0, :expired => false, :archived => false).paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def bookmark_stream_favorites
    Bookmark.where('user_id = ? and view_count > 0', current_user.id).order('view_count DESC').limit(30)
  end
  
  def bookmark_stream_by_site(site)
    Bookmark.where(:user_id => current_user.id, :site_id => site).order('created_at DESC')
  end
  
  # return a random selection of bookmarks; just a crude implementation, should be optimized with e.g. caching for some time
  def bookmark_stream_featured
    bookmarks = Bookmark.where(user_id: current_user.id, expired: false,  archived: false)
    
    features = []
    n = bookmarks.count -  1
    
    unless n < 16
      features << bookmarks[ Random.new.rand(0..n)]
      features << bookmarks[ Random.new.rand(0..n)]
      features << bookmarks[ Random.new.rand(0..n)]
    end
    
    features
  end
  
  def bookmark_count_all(current_user)
    Bookmark.where(user_id: current_user.id).count
  end
  
  def bookmark_count_unread(current_user)
    Bookmark.where(user_id: current_user.id, view_count: 0).count
  end
  
  def bookmark_count_archived(current_user)
    Bookmark.where(user_id: current_user.id, archived: true).count
  end
  
end

app/helpers/bookmarks_helper.rb
require 'uri'

module BookmarksHelper
  
  def format_date(date)
    date.to_s.split('UTC')[0].strip!
  end
  
  def favicon_tag(site_id)
    "<img class='favicon-img' src='#{root_path + 'favicons/' + Site.find(site_id).favicon}' />".html_safe
  end
  
  def bookmarks_by_site(site_id) 
    host = Site.find(site_id).host
    "<a href='/s/#{site_id}'>#{host}</a>".html_safe
  end
  
  def bookmark_host(site_id) 
    host = Site.find(site_id).host
    "<a href='http://#{host}' target='_blank'>#{host}</a>".html_safe
  end
  
end

app/views/bookmarks/_bookmark.html.erb
<% if bookmark.time_to_expiration < 16 %>
<div class='bookmark-expired'>
<% elsif bookmark.view_count == 0 %>
<div class='bookmark-unread'>
<% else %>
<div class='bookmark'>
<% end %>
	
	<div class='bookmark-favicon'>
		<%= favicon_tag bookmark.site_id %>
	</div>


	<div class='bookmark-meta'>
		<div class='bookmark-title'>
			<%= link_to bookmark.description, "/r/#{bookmark.url_shortened}", :target => '_blank' %>
		</div>
		<div class='bookmark-site'>
			<%= bookmarks_by_site bookmark.site_id %> . Added <%= timeago(bookmark.created_at) %> 
			<% if !bookmark.archived %>
				. <%= bookmark.time_to_expiration %> days left
			<% end %>
		</div>
	</div>
	
	<div class='bookmark-meta2'>
		<div class='bookmark-controls-top'>
			
		</div>
		<div class='bookmark-controls-bottom'>
			<% if !bookmark.archived %>
				<%= link_to("archive", "/a/#{bookmark.id}", :method => :post) %>
			<% end %>
			<%= link_to 'edit', edit_bookmark_path(bookmark) %>
			<%= link_to 'delete', bookmark, method: :delete %>
		</div>
	</div>

</div>

app/views/bookmarks/_bookmark_top.html.erb
<div class="large-6 columns">
	<ul class="inline-list ">
		<li><%= link_to 'ALL', root_path %></li>
		<li><%= link_to 'FAVORITES', '/f' %></li>
		<li><%= link_to 'OLDEST', '/o' %></li>
		<li><%= link_to 'ARCHIVE', '/a' %></li>
	</ul>
</div>

<div class="large-6 columns">
	<div class="bookmarks-stats">You curated
		<%= @bookmark_count_all %> links so far.
		<% if @bookmark_count_unread > 0 %>
			<%= link_to "#{@bookmark_count_unread} are still unread.", '/n' %>
		<% end %>
		<% if @bookmark_count_archived > 0 %>
			<%= link_to "#{@bookmark_count_archived} archived.", '/a' %>
		<% end %>
	</div>
</div>

app/views/bookmarks/_feature.html.erb
<div class='bookmark-featured'>
	<div class='bookmark-favicon'>
		<%= favicon_tag feature.site_id %>
	</div>


	<div class='bookmark-meta'>
		<div class='bookmark-title'>
			<%= link_to feature.description, "/r/#{feature.url_shortened}", :target => '_blank' %>
		</div>
		<div class='bookmark-site'>
			<%= bookmarks_by_site feature.site_id %> . Added <%= timeago(feature.created_at) %> . <%= feature.time_to_expiration %> days left
		</div>
	</div>
	
	<div class='bookmark-meta2'>
		<div class='bookmark-controls-top'>
			
		</div>
		<div class='bookmark-controls-bottom'>
			<%= link_to("archive", "/a/#{feature.id}", :method => :post) %>
			<%= link_to 'edit', edit_bookmark_path(feature) %>
			<%= link_to 'delete', feature, method: :delete %>
		</div>
	</div>

</div>

app/views/bookmarks/edit.html.erb
<div class="row content">
	<%= render 'bookmark_top' %>
	
	<div class="bookmark-form">
		<%= form_for(@bookmark, :html => { :role => 'form'}) do |f| %>
		
			<%= f.label :Description %>
			<%= f.text_field :description, :autofocus => true, class: 'form-control' %>
	    	
			<div class="form-control">
				<%= f.submit 'Update', :class => 'button left [secondary success alert]' %>
			</div>
			<div class="form-alt-control">
				or <%= link_to 'Cancel', bookmarks_path %>
			</div>
	 	<% end %>
	</div>
</div>

app/views/bookmarks/favorites.html.erb
<% content_for :pre_js do %>
<script>
	$('document').ready(function() {	
		if(intervalID != -1000)
			clearInterval(intervalID);
	})
</script>
<% end %>

<div class="row content">
	<%= render 'bookmark_top' %>
	
	<div class="small-12 columns bookmarks">
		<div class="bookmark-input">
			<%= form_for(@bookmark) do |f| %>
			<%= text_field_tag :url, params[:url], class: "b-input", id: "appendedInputButton", placeholder: "Add a new bookmark…"  %>
			<% end %>
		</div>
		<% if !@bookmarks.blank?%>
		<div class="bookmarks-stream-noscroll">
			<%= render :partial => "bookmark", :collection => @bookmarks%>
		</div>
		<% end %>
	</div>
</div>

<%= javascript_tag do %>
  $(function() {
    $("time.timeago").timeago();
  });
<% end %>

app/views/bookmarks/index.html.erb
<% content_for :pre_js do %>
<script>
	$(function() {
  	  $("time.timeago").timeago();
	});

	$('document').ready(function() {
		intervalID = setInterval(checkScroll, 200);
	})
</script>
<% end %>

<div class="row content">
	<%= render 'bookmark_top' %>
	
	<div class="small-12 columns bookmarks">
		<div class="bookmark-input">
			<%= form_for(@bookmark) do |f| %>
			<%= text_field_tag :url, params[:url], class: "b-input", id: "appendedInputButton", placeholder: "Add a new bookmark…"  %>
			<% end %>
		</div>
		<% if !@features.blank? %>
		<div class="features-stream">
			<%= render :partial => "feature", :collection => @features %>
			<hr/>
		</div>
		<% end %>
		<% if !@bookmarks.blank? %>
		<div class="bookmarks-stream">
			<%= render :partial => "bookmark", :collection => @bookmarks %>
		</div>
		<% end %>
	</div>
</div>

app/views/bookmarks/index_noscroll.html.erb
<% content_for :pre_js do %>
<script>
	$('document').ready(function() {	
		if(intervalID != -1000)
			clearInterval(intervalID);
	})
</script>
<% end %>

<div class="row content">
	<%= render 'bookmark_top' %>
	
	<div class="small-12 columns bookmarks">
		<div class="bookmark-input">
			<%= form_for(@bookmark) do |f| %>
			<%= text_field_tag :url, params[:url], class: "b-input", id: "appendedInputButton", placeholder: "Add a new bookmark…"  %>
			<% end %>
		</div>
		<% if !@bookmarks.blank?%>
		<div class="bookmarks-stream-noscroll">
			<%= render :partial => "bookmark", :collection => @bookmarks%>
		</div>
		<% end %>
	</div>
</div>

<%= javascript_tag do %>
  $(function() {
    $("time.timeago").timeago();
  });
<% end %>